#!/bin/sh

export PATH=$PATH:/opt/node/bin
export SCREEN_DEVICE="/dev/ttyACM0"
export APP_NAME="demo2"
#export ZETTA_CLOUD="ws://10.0.0.126:3000"


NODE_ENV="production"
NODE_APP='app'
APP_DIR='/home/pi/robotics-demo';
PID_FILE=$APP_DIR/pid/app.pid
LOG_FILE=$APP_DIR/log/app.log
CONFIG_DIR=$APP_DIR/config
PORT=3000
# NODE_EXEC=`which zetta`
NODE_EXEC='/opt/node/bin/zetta'

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: node-app is the script for starting a node app on boot.
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop node
# Description: Node process for app
### END INIT INFO

start_app (){
    if [ -f $PID_FILE ]
    then
        # echo "$PID_FILE exists, process is already running or crashed"
        # exit 1
	stop_app
    fi
	cd $APP_DIR

	HOSTNAME=`hostname`
	echo $APP_DIR/${HOSTNAME}_registry.json $APP_DIR/registry.json
	cp $APP_DIR/${HOSTNAME}_registry.json $APP_DIR/registry.json

	echo "Starting node app..."
	echo "$NODE_EXEC run --app $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &"
	$NODE_EXEC run --app $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &
	echo $! > $PID_FILE;
	wait $!

	if [ -f $PID_FILE ]; then
		rm -f $PID_FILE
	fi
}

stop_app (){
    if [ ! -f $PID_FILE ]
    then
        echo "$PID_FILE does not exist, process is not running"
        exit 1
    else
        echo "Stopping $APP_DIR/$NODE_APP ..."
        echo "Killing `cat $PID_FILE`"
        kill `cat $PID_FILE`;
        rm -f $PID_FILE;
        echo "Node stopped"
    fi
}

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        if [ -f $PID_FILE ]
        then
            PID=`cat $PID_FILE`
            if [ -z "`ps ef | awk '{print $1}' | grep "^$PID$"`" ]
            then
                echo "Node app stopped but pid file exists"
            else
                echo "Node app running with pid $PID"

            fi
        else
            echo "Node app stopped"
        fi
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac
